version: '3'

services:
  primary:
    image: postgres:13
    container_name: postgres_primary
    restart: always
    volumes:
        - ./data:/var/lib/postgresql/data
        - ./my-postgres.conf:/etc/postgresql/postgresql.conf
        - ./my-pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=b0ndP0stGres'
      - 'POSTGRES_DB=BondAdvance'