
version: '3'

services:
  pg-primary:
    image: 'postgres:13'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data'
    ports:
     - '5432:5432'

  pg-secondary:
    image: 'postgres:13'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data'
      REPLICATE_FROM: 'pg-primary'
    ports:
     - '5433:5432'
    links:
     - 'pg-primary'
